-- ============================================================
-- Creation date    : dateRTY
-- Description      : projet 
-- ============================================================ 
CREATE USER SCHEMA1 IDENTIFIED BY SCHEMA1 DEFAULT TABLESPACE NAMESPACE1;
ALTER USER SCHEMA1 ACCOUNT UNLOCK;
GRANT CREATE SESSION TO SCHEMA1;
GRANT CREATE table, CREATE procedure, CREATE synonym, CREATE view TO SCHEMA1;
GRANT UNLIMITED TABLESPACE TO SCHEMA1;
GRANT DEBUG, EXECUTE ON SCHEMA3.PACKAGE_PRINT TO SCHEMA1;
GRANT DEBUG, EXECUTE ON SCHEMA3.PACKAGE_07 TO SCHEMA1;
GRANT SELECT ON SCHEMA3.TAB_98 TO SCHEMA1;
GRANT SELECT ON SCHEMA3.TAB_99 TO SCHEMA1;